version: "3.9"
services:
  valora-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: valora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Asia/Kolkata"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
  pgdata:
